self.include("A")
self.include("B")
self.include("smart_pointer")
self.include("serial")
self.include("map")
self.include("registry")
self.include("weak_ptr")
self.include("tuple")
self.include("object_map")
self.include("factory_map")

